version: '3.9'

services:
  e2e:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - BACKEND_URL=${BACKEND_URL}
      - TEST_FILE=${TEST_FILE}
    networks:
      - dev_network

networks:
  dev_network:
    external: true
