name: Create PR from Issue Comment

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pr:
    if: startsWith(github.event.comment.body, 'create-pr ')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract branch name
        id: extract_branch
        run: |
          echo "branch_name=$(echo '${{ github.event.comment.body }}' | sed 's/^create-pr //')" >> $GITHUB_OUTPUT

      - name: Check if branch exists
        run: |
          if git ls-remote --heads origin ${{ steps.extract_branch.outputs.branch_name }} | grep ${{ steps.extract_branch.outputs.branch_name }}; then
            echo "Branch exists."
          else
            echo "Branch does not exist."
            exit 1
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ steps.extract_branch.outputs.branch_name }}
          branch: ${{ steps.extract_branch.outputs.branch_name }}
          base: main
          title: "Linking PR to Issue #${{ github.event.issue.number }}"
          body: "This PR is automatically created and linked to Issue #${{ github.event.issue.number }}."
          assignees: ${{ github.event.issue.user.login }}
