name: Issue作成時に自動コメントを追加

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Issueにコメントする
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.issue.number;

            const commentBody = `
            issueにコメントできるコマンド一覧

            create-pr [ブランチ名]
            `;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: commentBody.trim()
            });
